ALTER TABLE weather ADD column wind_direction;
ALTER TABLE weather add column wind_speed;

ALTER TABLE weather DROP COLUMN wind_direction_speed;

--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "SEP"."WEATHER" 
   (	"ID" NUMBER, 
	"PRESSURE" VARCHAR2(20 BYTE), 
	"DEW_POINT_TEMPERATURE" NUMBER, 
	"SURFACE_TEMPERATURE" NUMBER, 
	"CLOUD_COVER" VARCHAR2(20 BYTE), 
	"VISIBILITY" VARCHAR2(20 BYTE), 
	"ISSUING_AIRPORT" VARCHAR2(20 BYTE), 
	"WIND_DIRECTION" VARCHAR2(20 BYTE), 
	"WIND_SPEED" VARCHAR2(20 BYTE), 
	"DATE_TIME" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEATHER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEP"."WEATHER_ID" ON "SEP"."WEATHER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "SEP"."WEATHER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("PRESSURE" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("DEW_POINT_TEMPERATURE" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("SURFACE_TEMPERATURE" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("CLOUD_COVER" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("VISIBILITY" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" MODIFY ("ISSUING_AIRPORT" NOT NULL ENABLE);
  ALTER TABLE "SEP"."WEATHER" ADD CONSTRAINT "WEATHER_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
